package com.brucechou.object.provider;

import com.brucechou.object.ObjectFactory;

import java.util.Random;

/**
 * An interface provides a random size generated by object factory and random.
 */
public interface WithRandomSize {

    /**
     * Get random size for collection, map, stream, array, etc.
     *
     * @param objectFactory object factory
     * @param random random
     * @return a random size generated
     */
    default int getRandomSize(ObjectFactory objectFactory, Random random) {
        return random.nextInt(objectFactory.getMaxSize() - objectFactory.getMinSize() + 1)
                       + objectFactory.getMinSize();
    }

}
